---
- name: This is a hello-world example
  hosts: hosts
  tasks:
    - name: Create a file called '/tmp/testfile.txt' with the content 'hello world'.
      copy:
        content: hello worldn
        dest: /tmp/testfile.txt
    - name: Listing the files using shell module
      shell:
        echo "hai"; ls -lrt /tmp/